name: vitrine
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0"

dependencies:
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.8.2
  flutter_local_notifications: ^9.1.4
  google_fonts: ^6.2.1
  hue_rotation: ^1.2.1
  image_picker: ^0.8.4+2
  mdi: 5.0.0-nullsafety.0
  meta: ^1.11.0
  page_view_indicators: ^2.0.0
  shimmer: ^2.0.0
  test: ^1.24.9
  url_launcher: ^6.2.5
  uuid: ^3.0.5

dev_dependencies:
  faker: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.6.0
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/categories/
