name: vitrine
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  firebase_storage: ^10.0.2
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  image_picker: ^0.8.4+2
  mdi: ^4.0.0
  page_view_indicators: ^2.0.0
  url_launcher: ^6.0.12
  uuid: ^3.0.5

dev_dependencies:
  faker: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.6.0
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
